package com.example.gamechangermobile.database

import com.beust.klaxon.JsonReader
import com.beust.klaxon.Klaxon
import java.io.StringReader


//var dataList = StatsParser().parse(test_json)
//Log.d("Debug", "id 0: " + dataList?.get(0)?.info?.opponent_team_name.toString())
//Log.d("Debug", "id 1: " + dataList?.get(1)?.info?.opponent_team_name.toString())

class StatsParser() {
    fun parse_player_game_data(data: String): ArrayList<GCResponse> {
        val dataList = arrayListOf<GCResponse>()

        JsonReader(StringReader(data)).use { reader ->
            reader.beginArray {
                while (reader.hasNext()) {
                    val d = Klaxon().parse<GCResponse>(reader)
                    dataList.add(d!!)
                }
            }
        }
        return dataList
    }
}

class GCResponse(val info: Info = Info(), val box: Box = Box()) {

}

class Info(
    val id: Int = 0,
    val state: String = "",
    val player_name: String = "",
    val player_jersey_number: Int = 0,
    val team_name: String = "",
    val team_pts: Int = 0,
    val opponent_team_name: String = "",
    val opponent_team_pts: Int = 0,
    val is_home: Boolean = false,
    val is_win: Boolean = false,
    val game_id: Int = 0,
    val game_date: String = "",
    val game_name: String = "",
    val game_category: Game_Category = Game_Category(),
    val is_starter: Boolean = false,
) {

}

class Box(
    val ft_a: Int = 0,
    val three_pts_percent: Float = 0.0F,
    val min: Int = 0,
    val two_pts_a: Int = 0,
    val reb: Int = 0,
    val off_reb: Int = 0,
    val ft_percent: Float = 0.0F,
    val three_pts_a: Int = 0,
    val blk: Int = 0,
    val two_pts: Int = 0,
    val eff: Int = 0,
    val stl: Int = 0,
    val to: Int = 0,
    val fg_pts: Int = 0,
    val two_pts_percent: Float = 0.0F,
    val ft_pts: Int = 0,
    val two_pts_m: Int = 0,
    val pf: Int = 0,
    val three_pts: Int = 0,
    val def_reb: Int = 0,
    val play: Int = 0,
    val fg_a: Int = 0,
    val three_pts_m: Int = 0,
    val pts: Int = 0,
    val fg_m: Int = 0,
    val ft_m: Int = 0,
    val ast: Int = 0,
    val fg_percent: Float = 0.0F
) {}

class Game_Category(
    val id: Int = 0,
    val name: String = "",
    val description: String = "",
    val start_date: String = "",
    val end_date: String = ""
) {

}


val test_json =
    """
[
{
    "info": {
    "id": 378,
    "state": "ALL",
    "player_name": "辛巴",
    "player_jersey_number": 35,
    "team_name": "新竹街口攻城獅",
    "team_pts": 86,
    "opponent_team_name": "福爾摩沙台新夢想家",
    "opponent_team_pts": 80,
    "is_home": true,
    "is_win": true,
    "game_id": 279,
    "game_date": "2022-01-09T06:30:00Z",
    "game_name": "G21",
    "game_category": {
    "id": 19,
    "name": "例行賽",
    "description": "",
    "start_date": "2021-11-30T16:00:00Z",
    "end_date": "2022-05-08T16:00:00Z"
},
    "is_starters": true
},
    "box": {
    "ft_a": 14,
    "three_pts_percent": 0,
    "min": 2569,
    "two_pts_a": 22,
    "reb": 31,
    "off_reb": 16,
    "ft_percent": 0.714,
    "three_pts_a": 0,
    "blk": 6,
    "two_pts": 24,
    "eff": 55,
    "stl": 0,
    "to": 2,
    "fg_pts": 24,
    "two_pts_percent": 0.545,
    "ft_pts": 10,
    "two_pts_m": 12,
    "pf": 2,
    "three_pts": 0,
    "def_reb": 15,
    "play": 30,
    "fg_a": 22,
    "three_pts_m": 0,
    "pts": 34,
    "fg_m": 12,
    "ft_m": 10,
    "ast": 0,
    "fg_percent": 0.545
}
},
{
    "info": {
    "id": 378,
    "state": "ALL",
    "player_name": "辛巴",
    "player_jersey_number": 35,
    "team_name": "新竹街口攻城獅",
    "team_pts": 95,
    "opponent_team_name": "桃園領航猿",
    "opponent_team_pts": 83,
    "is_home": false,
    "is_win": true,
    "game_id": 268,
    "game_date": "2021-12-19T09:00:00Z",
    "game_name": "G10",
    "game_category": {
    "id": 19,
    "name": "例行賽",
    "description": "",
    "start_date": "2021-11-30T16:00:00Z",
    "end_date": "2022-05-08T16:00:00Z"
},
    "is_starters": true
},
    "box": {
    "ft_a": 11,
    "three_pts_percent": 0,
    "min": 2557,
    "two_pts_a": 21,
    "reb": 27,
    "off_reb": 7,
    "ft_percent": 0.364,
    "three_pts_a": 0,
    "blk": 2,
    "two_pts": 28,
    "eff": 49,
    "stl": 1,
    "to": 2,
    "fg_pts": 28,
    "two_pts_percent": 0.667,
    "ft_pts": 4,
    "two_pts_m": 14,
    "pf": 1,
    "three_pts": 0,
    "def_reb": 20,
    "play": 32,
    "fg_a": 21,
    "three_pts_m": 0,
    "pts": 32,
    "fg_m": 14,
    "ft_m": 4,
    "ast": 3,
    "fg_percent": 0.667
}
},
{
    "info": {
    "id": 378,
    "state": "ALL",
    "player_name": "辛巴",
    "player_jersey_number": 35,
    "team_name": "新竹街口攻城獅",
    "team_pts": 96,
    "opponent_team_name": "新北國王",
    "opponent_team_pts": 111,
    "is_home": true,
    "is_win": false,
    "game_id": 307,
    "game_date": "2022-03-06T09:00:00Z",
    "game_name": "G49",
    "game_category": {
    "id": 19,
    "name": "例行賽",
    "description": "",
    "start_date": "2021-11-30T16:00:00Z",
    "end_date": "2022-05-08T16:00:00Z"
},
    "is_starters": true
},
    "box": {
    "ft_a": 13,
    "three_pts_percent": 1.0,
    "min": 2479,
    "two_pts_a": 13,
    "reb": 14,
    "off_reb": 4,
    "ft_percent": 0.692,
    "three_pts_a": 1,
    "blk": 0,
    "two_pts": 22,
    "eff": 39,
    "stl": 0,
    "to": 3,
    "fg_pts": 25,
    "two_pts_percent": 0.846,
    "ft_pts": 9,
    "two_pts_m": 11,
    "pf": 6,
    "three_pts": 3,
    "def_reb": 10,
    "play": 24,
    "fg_a": 14,
    "three_pts_m": 1,
    "pts": 34,
    "fg_m": 12,
    "ft_m": 9,
    "ast": 0,
    "fg_percent": 0.857
}
},
{
    "info": {
    "id": 378,
    "state": "ALL",
    "player_name": "辛巴",
    "player_jersey_number": 35,
    "team_name": "新竹街口攻城獅",
    "team_pts": 89,
    "opponent_team_name": "桃園領航猿",
    "opponent_team_pts": 97,
    "is_home": true,
    "is_win": false,
    "game_id": 317,
    "game_date": "2022-03-25T11:00:00Z",
    "game_name": "G59",
    "game_category": {
    "id": 19,
    "name": "例行賽",
    "description": "",
    "start_date": "2021-11-30T16:00:00Z",
    "end_date": "2022-05-08T16:00:00Z"
},
    "is_starters": true
},
    "box": {
    "ft_a": 17,
    "three_pts_percent": 0,
    "min": 2474,
    "two_pts_a": 17,
    "reb": 22,
    "off_reb": 9,
    "ft_percent": 0.294,
    "three_pts_a": 0,
    "blk": 3,
    "two_pts": 18,
    "eff": 33,
    "stl": 2,
    "to": 0,
    "fg_pts": 18,
    "two_pts_percent": 0.529,
    "ft_pts": 5,
    "two_pts_m": 9,
    "pf": 3,
    "three_pts": 0,
    "def_reb": 13,
    "play": 24,
    "fg_a": 17,
    "three_pts_m": 0,
    "pts": 23,
    "fg_m": 9,
    "ft_m": 5,
    "ast": 3,
    "fg_percent": 0.529
}
},
{
    "info": {
    "id": 378,
    "state": "ALL",
    "player_name": "辛巴",
    "player_jersey_number": 35,
    "team_name": "新竹街口攻城獅",
    "team_pts": 103,
    "opponent_team_name": "高雄鋼鐵人",
    "opponent_team_pts": 95,
    "is_home": false,
    "is_win": true,
    "game_id": 308,
    "game_date": "2022-03-12T06:30:00Z",
    "game_name": "G50",
    "game_category": {
    "id": 19,
    "name": "例行賽",
    "description": "",
    "start_date": "2021-11-30T16:00:00Z",
    "end_date": "2022-05-08T16:00:00Z"
},
    "is_starters": true
},
    "box": {
    "ft_a": 14,
    "three_pts_percent": 0,
    "min": 2398,
    "two_pts_a": 13,
    "reb": 20,
    "off_reb": 0,
    "ft_percent": 0.571,
    "three_pts_a": 0,
    "blk": 4,
    "two_pts": 24,
    "eff": 49,
    "stl": 1,
    "to": 1,
    "fg_pts": 24,
    "two_pts_percent": 0.923,
    "ft_pts": 8,
    "two_pts_m": 12,
    "pf": 2,
    "three_pts": 0,
    "def_reb": 20,
    "play": 21,
    "fg_a": 13,
    "three_pts_m": 0,
    "pts": 32,
    "fg_m": 12,
    "ft_m": 8,
    "ast": 0,
    "fg_percent": 0.923
}
},
{
    "info": {
    "id": 378,
    "state": "ALL",
    "player_name": "辛巴",
    "player_jersey_number": 35,
    "team_name": "新竹街口攻城獅",
    "team_pts": 105,
    "opponent_team_name": "高雄鋼鐵人",
    "opponent_team_pts": 95,
    "is_home": true,
    "is_win": true,
    "game_id": 264,
    "game_date": "2021-12-12T09:00:00Z",
    "game_name": "G06",
    "game_category": {
    "id": 19,
    "name": "例行賽",
    "description": "",
    "start_date": "2021-11-30T16:00:00Z",
    "end_date": "2022-05-08T16:00:00Z"
},
    "is_starters": true
},
    "box": {
    "ft_a": 8,
    "three_pts_percent": 0,
    "min": 2381,
    "two_pts_a": 14,
    "reb": 26,
    "off_reb": 7,
    "ft_percent": 0.625,
    "three_pts_a": 0,
    "blk": 7,
    "two_pts": 20,
    "eff": 52,
    "stl": 2,
    "to": 4,
    "fg_pts": 20,
    "two_pts_percent": 0.714,
    "ft_pts": 5,
    "two_pts_m": 10,
    "pf": 2,
    "three_pts": 0,
    "def_reb": 19,
    "play": 24,
    "fg_a": 14,
    "three_pts_m": 0,
    "pts": 25,
    "fg_m": 10,
    "ft_m": 5,
    "ast": 3,
    "fg_percent": 0.714
}
},
{
    "info": {
    "id": 378,
    "state": "ALL",
    "player_name": "辛巴",
    "player_jersey_number": 35,
    "team_name": "新竹街口攻城獅",
    "team_pts": 101,
    "opponent_team_name": "桃園領航猿",
    "opponent_team_pts": 80,
    "is_home": true,
    "is_win": true,
    "game_id": 291,
    "game_date": "2022-02-12T09:00:00Z",
    "game_name": "G33",
    "game_category": {
    "id": 19,
    "name": "例行賽",
    "description": "",
    "start_date": "2021-11-30T16:00:00Z",
    "end_date": "2022-05-08T16:00:00Z"
},
    "is_starters": true
},
    "box": {
    "ft_a": 5,
    "three_pts_percent": 0,
    "min": 2369,
    "two_pts_a": 13,
    "reb": 15,
    "off_reb": 5,
    "ft_percent": 0.8,
    "three_pts_a": 0,
    "blk": 1,
    "two_pts": 18,
    "eff": 33,
    "stl": 1,
    "to": 4,
    "fg_pts": 18,
    "two_pts_percent": 0.692,
    "ft_pts": 4,
    "two_pts_m": 9,
    "pf": 3,
    "three_pts": 0,
    "def_reb": 10,
    "play": 21,
    "fg_a": 13,
    "three_pts_m": 0,
    "pts": 22,
    "fg_m": 9,
    "ft_m": 4,
    "ast": 3,
    "fg_percent": 0.692
}
},
{
    "info": {
    "id": 378,
    "state": "ALL",
    "player_name": "辛巴",
    "player_jersey_number": 35,
    "team_name": "新竹街口攻城獅",
    "team_pts": 97,
    "opponent_team_name": "高雄鋼鐵人",
    "opponent_team_pts": 98,
    "is_home": true,
    "is_win": false,
    "game_id": 277,
    "game_date": "2022-01-08T06:30:00Z",
    "game_name": "G19",
    "game_category": {
    "id": 19,
    "name": "例行賽",
    "description": "",
    "start_date": "2021-11-30T16:00:00Z",
    "end_date": "2022-05-08T16:00:00Z"
},
    "is_starters": true
},
    "box": {
    "ft_a": 10,
    "three_pts_percent": 0,
    "min": 2353,
    "two_pts_a": 18,
    "reb": 21,
    "off_reb": 9,
    "ft_percent": 0.9,
    "three_pts_a": 0,
    "blk": 1,
    "two_pts": 24,
    "eff": 47,
    "stl": 0,
    "to": 4,
    "fg_pts": 24,
    "two_pts_percent": 0.667,
    "ft_pts": 9,
    "two_pts_m": 12,
    "pf": 1,
    "three_pts": 0,
    "def_reb": 12,
    "play": 31,
    "fg_a": 18,
    "three_pts_m": 0,
    "pts": 33,
    "fg_m": 12,
    "ft_m": 9,
    "ast": 3,
    "fg_percent": 0.667
}
},
{
    "info": {
    "id": 378,
    "state": "ALL",
    "player_name": "辛巴",
    "player_jersey_number": 35,
    "team_name": "新竹街口攻城獅",
    "team_pts": 78,
    "opponent_team_name": "福爾摩沙台新夢想家",
    "opponent_team_pts": 84,
    "is_home": false,
    "is_win": false,
    "game_id": 282,
    "game_date": "2022-01-15T06:30:00Z",
    "game_name": "G24",
    "game_category": {
    "id": 19,
    "name": "例行賽",
    "description": "",
    "start_date": "2021-11-30T16:00:00Z",
    "end_date": "2022-05-08T16:00:00Z"
},
    "is_starters": true
},
    "box": {
    "ft_a": 8,
    "three_pts_percent": 0,
    "min": 2316,
    "two_pts_a": 14,
    "reb": 28,
    "off_reb": 10,
    "ft_percent": 0.625,
    "three_pts_a": 0,
    "blk": 3,
    "two_pts": 12,
    "eff": 33,
    "stl": 0,
    "to": 4,
    "fg_pts": 12,
    "two_pts_percent": 0.429,
    "ft_pts": 5,
    "two_pts_m": 6,
    "pf": 3,
    "three_pts": 0,
    "def_reb": 18,
    "play": 23,
    "fg_a": 14,
    "three_pts_m": 0,
    "pts": 17,
    "fg_m": 6,
    "ft_m": 5,
    "ast": 0,
    "fg_percent": 0.429
}
},
{
    "info": {
    "id": 378,
    "state": "ALL",
    "player_name": "辛巴",
    "player_jersey_number": 35,
    "team_name": "新竹街口攻城獅",
    "team_pts": 97,
    "opponent_team_name": "高雄鋼鐵人",
    "opponent_team_pts": 87,
    "is_home": true,
    "is_win": true,
    "game_id": 305,
    "game_date": "2022-03-05T09:00:00Z",
    "game_name": "G47",
    "game_category": {
    "id": 19,
    "name": "例行賽",
    "description": "",
    "start_date": "2021-11-30T16:00:00Z",
    "end_date": "2022-05-08T16:00:00Z"
},
    "is_starters": true
},
    "box": {
    "ft_a": 8,
    "three_pts_percent": 0,
    "min": 2276,
    "two_pts_a": 19,
    "reb": 18,
    "off_reb": 7,
    "ft_percent": 0.875,
    "three_pts_a": 0,
    "blk": 2,
    "two_pts": 20,
    "eff": 39,
    "stl": 1,
    "to": 3,
    "fg_pts": 20,
    "two_pts_percent": 0.526,
    "ft_pts": 7,
    "two_pts_m": 10,
    "pf": 1,
    "three_pts": 0,
    "def_reb": 11,
    "play": 28,
    "fg_a": 19,
    "three_pts_m": 0,
    "pts": 27,
    "fg_m": 10,
    "ft_m": 7,
    "ast": 4,
    "fg_percent": 0.526
}
},
{
    "info": {
    "id": 378,
    "state": "ALL",
    "player_name": "辛巴",
    "player_jersey_number": 35,
    "team_name": "新竹街口攻城獅",
    "team_pts": 74,
    "opponent_team_name": "福爾摩沙台新夢想家",
    "opponent_team_pts": 97,
    "is_home": false,
    "is_win": false,
    "game_id": 313,
    "game_date": "2022-03-19T06:30:00Z",
    "game_name": "G55",
    "game_category": {
    "id": 19,
    "name": "例行賽",
    "description": "",
    "start_date": "2021-11-30T16:00:00Z",
    "end_date": "2022-05-08T16:00:00Z"
},
    "is_starters": true
},
    "box": {
    "ft_a": 10,
    "three_pts_percent": 0,
    "min": 2263,
    "two_pts_a": 10,
    "reb": 14,
    "off_reb": 4,
    "ft_percent": 0.6,
    "three_pts_a": 0,
    "blk": 1,
    "two_pts": 12,
    "eff": 24,
    "stl": 0,
    "to": 3,
    "fg_pts": 12,
    "two_pts_percent": 0.6,
    "ft_pts": 6,
    "two_pts_m": 6,
    "pf": 2,
    "three_pts": 0,
    "def_reb": 10,
    "play": 22,
    "fg_a": 10,
    "three_pts_m": 0,
    "pts": 18,
    "fg_m": 6,
    "ft_m": 6,
    "ast": 2,
    "fg_percent": 0.6
}
},
{
    "info": {
    "id": 378,
    "state": "ALL",
    "player_name": "辛巴",
    "player_jersey_number": 35,
    "team_name": "新竹街口攻城獅",
    "team_pts": 101,
    "opponent_team_name": "新北國王",
    "opponent_team_pts": 80,
    "is_home": true,
    "is_win": true,
    "game_id": 273,
    "game_date": "2021-12-26T09:00:00Z",
    "game_name": "G15",
    "game_category": {
    "id": 19,
    "name": "例行賽",
    "description": "",
    "start_date": "2021-11-30T16:00:00Z",
    "end_date": "2022-05-08T16:00:00Z"
},
    "is_starters": true
},
    "box": {
    "ft_a": 12,
    "three_pts_percent": 0,
    "min": 1808,
    "two_pts_a": 15,
    "reb": 17,
    "off_reb": 2,
    "ft_percent": 0.417,
    "three_pts_a": 0,
    "blk": 0,
    "two_pts": 30,
    "eff": 44,
    "stl": 0,
    "to": 4,
    "fg_pts": 30,
    "two_pts_percent": 1.0,
    "ft_pts": 5,
    "two_pts_m": 15,
    "pf": 0,
    "three_pts": 0,
    "def_reb": 15,
    "play": 27,
    "fg_a": 15,
    "three_pts_m": 0,
    "pts": 35,
    "fg_m": 15,
    "ft_m": 5,
    "ast": 3,
    "fg_percent": 1.0
}
},
{
    "info": {
    "id": 378,
    "state": "ALL",
    "player_name": "辛巴",
    "player_jersey_number": 35,
    "team_name": "新竹街口攻城獅",
    "team_pts": 91,
    "opponent_team_name": "桃園領航猿",
    "opponent_team_pts": 65,
    "is_home": true,
    "is_win": true,
    "game_id": 288,
    "game_date": "2022-01-23T09:00:00Z",
    "game_name": "G30",
    "game_category": {
    "id": 19,
    "name": "例行賽",
    "description": "",
    "start_date": "2021-11-30T16:00:00Z",
    "end_date": "2022-05-08T16:00:00Z"
},
    "is_starters": true
},
    "box": {
    "ft_a": 4,
    "three_pts_percent": 0,
    "min": 1767,
    "two_pts_a": 11,
    "reb": 22,
    "off_reb": 10,
    "ft_percent": 0.25,
    "three_pts_a": 0,
    "blk": 2,
    "two_pts": 12,
    "eff": 28,
    "stl": 0,
    "to": 3,
    "fg_pts": 12,
    "two_pts_percent": 0.545,
    "ft_pts": 1,
    "two_pts_m": 6,
    "pf": 1,
    "three_pts": 0,
    "def_reb": 12,
    "play": 16,
    "fg_a": 11,
    "three_pts_m": 0,
    "pts": 13,
    "fg_m": 6,
    "ft_m": 1,
    "ast": 2,
    "fg_percent": 0.545
}
},
{
    "info": {
    "id": 378,
    "state": "ALL",
    "player_name": "辛巴",
    "player_jersey_number": 35,
    "team_name": "新竹街口攻城獅",
    "team_pts": 109,
    "opponent_team_name": "福爾摩沙台新夢想家",
    "opponent_team_pts": 94,
    "is_home": false,
    "is_win": true,
    "game_id": 234,
    "game_date": "2021-11-20T16:00:00.288000Z",
    "game_name": "G11",
    "game_category": {
    "id": 18,
    "name": "熱身賽",
    "description": "",
    "start_date": "2021-10-31T16:00:00Z",
    "end_date": "2021-11-29T16:00:00Z"
},
    "is_starters": true
},
    "box": {
    "ft_a": 16,
    "three_pts_percent": 0,
    "min": 1657,
    "two_pts_a": 21,
    "reb": 17,
    "off_reb": 8,
    "ft_percent": 0.562,
    "three_pts_a": 0,
    "blk": 3,
    "two_pts": 30,
    "eff": 49,
    "stl": 1,
    "to": 1,
    "fg_pts": 30,
    "two_pts_percent": 0.714,
    "ft_pts": 9,
    "two_pts_m": 15,
    "pf": 0,
    "three_pts": 0,
    "def_reb": 9,
    "play": 34,
    "fg_a": 21,
    "three_pts_m": 0,
    "pts": 39,
    "fg_m": 15,
    "ft_m": 9,
    "ast": 3,
    "fg_percent": 0.714
}
},
{
    "info": {
    "id": 378,
    "state": "ALL",
    "player_name": "辛巴",
    "player_jersey_number": 35,
    "team_name": "新竹街口攻城獅",
    "team_pts": 87,
    "opponent_team_name": "台北富邦勇士",
    "opponent_team_pts": 98,
    "is_home": true,
    "is_win": false,
    "game_id": 262,
    "game_date": "2021-12-11T09:00:00Z",
    "game_name": "G04",
    "game_category": {
    "id": 19,
    "name": "例行賽",
    "description": "",
    "start_date": "2021-11-30T16:00:00Z",
    "end_date": "2022-05-08T16:00:00Z"
},
    "is_starters": false
},
    "box": {
    "ft_a": 13,
    "three_pts_percent": 0,
    "min": 2724,
    "two_pts_a": 11,
    "reb": 22,
    "off_reb": 5,
    "ft_percent": 0.462,
    "three_pts_a": 0,
    "blk": 3,
    "two_pts": 14,
    "eff": 35,
    "stl": 0,
    "to": 2,
    "fg_pts": 14,
    "two_pts_percent": 0.636,
    "ft_pts": 6,
    "two_pts_m": 7,
    "pf": 3,
    "three_pts": 0,
    "def_reb": 17,
    "play": 23,
    "fg_a": 11,
    "three_pts_m": 0,
    "pts": 20,
    "fg_m": 7,
    "ft_m": 6,
    "ast": 3,
    "fg_percent": 0.636
}
},
{
    "info": {
    "id": 378,
    "state": "ALL",
    "player_name": "辛巴",
    "player_jersey_number": 35,
    "team_name": "新竹街口攻城獅",
    "team_pts": 94,
    "opponent_team_name": "台北富邦勇士",
    "opponent_team_pts": 97,
    "is_home": true,
    "is_win": false,
    "game_id": 231,
    "game_date": "2021-11-19T16:00:00.288000Z",
    "game_name": "G08",
    "game_category": {
    "id": 18,
    "name": "熱身賽",
    "description": "",
    "start_date": "2021-10-31T16:00:00Z",
    "end_date": "2021-11-29T16:00:00Z"
},
    "is_starters": false
},
    "box": {
    "ft_a": 7,
    "three_pts_percent": 0,
    "min": 2248,
    "two_pts_a": 14,
    "reb": 15,
    "off_reb": 2,
    "ft_percent": 0.571,
    "three_pts_a": 0,
    "blk": 2,
    "two_pts": 16,
    "eff": 29,
    "stl": 1,
    "to": 1,
    "fg_pts": 16,
    "two_pts_percent": 0.571,
    "ft_pts": 4,
    "two_pts_m": 8,
    "pf": 2,
    "three_pts": 0,
    "def_reb": 13,
    "play": 21,
    "fg_a": 14,
    "three_pts_m": 0,
    "pts": 20,
    "fg_m": 8,
    "ft_m": 4,
    "ast": 1,
    "fg_percent": 0.571
}
},
{
    "info": {
    "id": 378,
    "state": "ALL",
    "player_name": "辛巴",
    "player_jersey_number": 35,
    "team_name": "新竹街口攻城獅",
    "team_pts": 114,
    "opponent_team_name": "台北富邦勇士",
    "opponent_team_pts": 106,
    "is_home": false,
    "is_win": true,
    "game_id": 274,
    "game_date": "2022-01-01T09:00:00Z",
    "game_name": "G16",
    "game_category": {
    "id": 19,
    "name": "例行賽",
    "description": "",
    "start_date": "2021-11-30T16:00:00Z",
    "end_date": "2022-05-08T16:00:00Z"
},
    "is_starters": false
},
    "box": {
    "ft_a": 10,
    "three_pts_percent": 0,
    "min": 2186,
    "two_pts_a": 15,
    "reb": 13,
    "off_reb": 3,
    "ft_percent": 0.5,
    "three_pts_a": 0,
    "blk": 2,
    "two_pts": 20,
    "eff": 31,
    "stl": 1,
    "to": 3,
    "fg_pts": 20,
    "two_pts_percent": 0.667,
    "ft_pts": 5,
    "two_pts_m": 10,
    "pf": 1,
    "three_pts": 0,
    "def_reb": 10,
    "play": 24,
    "fg_a": 15,
    "three_pts_m": 0,
    "pts": 25,
    "fg_m": 10,
    "ft_m": 5,
    "ast": 3,
    "fg_percent": 0.667
}
},
{
    "info": {
    "id": 378,
    "state": "ALL",
    "player_name": "辛巴",
    "player_jersey_number": 35,
    "team_name": "新竹街口攻城獅",
    "team_pts": 82,
    "opponent_team_name": "台北富邦勇士",
    "opponent_team_pts": 92,
    "is_home": true,
    "is_win": false,
    "game_id": 271,
    "game_date": "2021-12-25T09:00:00Z",
    "game_name": "G13",
    "game_category": {
    "id": 19,
    "name": "例行賽",
    "description": "",
    "start_date": "2021-11-30T16:00:00Z",
    "end_date": "2022-05-08T16:00:00Z"
},
    "is_starters": false
},
    "box": {
    "ft_a": 6,
    "three_pts_percent": 0,
    "min": 2144,
    "two_pts_a": 7,
    "reb": 11,
    "off_reb": 2,
    "ft_percent": 0.667,
    "three_pts_a": 0,
    "blk": 0,
    "two_pts": 12,
    "eff": 24,
    "stl": 0,
    "to": 2,
    "fg_pts": 12,
    "two_pts_percent": 0.857,
    "ft_pts": 4,
    "two_pts_m": 6,
    "pf": 2,
    "three_pts": 0,
    "def_reb": 9,
    "play": 14,
    "fg_a": 7,
    "three_pts_m": 0,
    "pts": 16,
    "fg_m": 6,
    "ft_m": 4,
    "ast": 2,
    "fg_percent": 0.857
}
}
]
"""